# Generated by Django 2.2.5 on 2019-12-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20191218_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
