# Generated by Django 3.0 on 2020-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('pprice', models.FloatField()),
                ('pbrand', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
