# Generated by Django 2.2.5 on 2019-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=40)),
                ('mobile', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
    ]
