# Generated by Django 2.2.5 on 2019-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.TextField(),
        ),
    ]
