# Generated by Django 2.2.5 on 2019-12-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20191214_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
