# Generated by Django 2.2.5 on 2019-12-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20191214_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
