# Generated by Django 2.2.5 on 2019-12-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
