# Generated by Django 2.2.5 on 2020-01-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
