# Generated by Django 3.0 on 2020-01-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=50, upload_to='')),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
